server:
  port: ${SERVER_PORT:8081}

spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/paymentdb}
      auto-index-creation: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: payment-service-group
      auto-offset-reset: earliest
    producer:
      properties:
        auto.register.schemas: false
        use.latest.version: true

schema:
  registry:
    url: ${SCHEMA_REGISTRY_URL:http://localhost:8081}

external:
  random-api:
    url: ${EXTERNAL_RANDOM_API_URL:http://localhost:9999/random}

kafka:
  topic:
    payment: CREATE_PAYMENT
    payment-result: PAYMENT_RESULT

internal:
  secret: ${INTERNAL_SECRET:dev-secret}