spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/paymentdb}
      auto-index-creation: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  liquibase:
    enabled: false

external:
  random-api:
    url: http://localhost:9999/random

kafka:
  topic:
    payment: CREATE_PAYMENT

internal:
  secret: ${INTERNAL_SECRET:dev-secret}